Repository gliff-ai/support, pull requests merged in 2022-01, with the labels that each got.

#22 Getstarted
  accountcustom.md
  adduser.md
  annotate.md
  assign.md
  basics.md
  createproject.md
  curate.md
  curatedata.md
  firststeps.md
  getstarted.md
  imagelabels.md
  index.md
  labels.md
  manage.md
  paintbrush.md
  setup.md
  splines.md
  whatis.md
Labels: documentation

#24 🔨 feat: standardise repo labels
  .github/labels.yml
  .github/workflows/apply-labels.yml
Labels: enhancement

#25 fix: first half of feedback changes
  adduser.md
  assign.md
  basics.md
  createproject.md
  getstarted.md
  setup.md
  whatis.md
Labels: bug
